apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-167481594
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-167481594
    app.kubernetes.io/part-of: test-app-167481588
  name: go-167481594
  namespace: skhileri
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-167481594
    weight: 100
status: {}
