apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-167481594
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-167481594
    app.kubernetes.io/part-of: test-app-167481588
  name: go-167481594
  namespace: skhileri
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-167481594
status:
  loadBalancer: {}
